Edit profile pages post
hsha0/CodeU-Spring2018-Team19 pull request #38
Opened 2018-04-26 00:12 UTC by CalamariDude

I might need to double check indentation.

2018-04-26 23:17 UTC, hsha0 requested changes

2018-04-26 23:17 UTC, hsha0 commented on src/main/java/codeu/controller/UsersServlet.java
> +	if (username == null) {
It's in my part, lol. Indentation should be 4 spaces

2018-04-26 23:17 UTC, hsha0 commented on src/main/java/codeu/controller/UsersServlet.java
> +	User user = userStore.getUser(username);
My part again. Indentation should be 4 spaces

2018-04-26 23:17 UTC, hsha0 commented on src/main/java/codeu/controller/UsersServlet.java
> +	  request.getRequestDispatcher("/WEB-INF/view/users.jsp").forward(request, response);
indentation should be 4 spaces. (I must mess up with space and tab before...)

2018-04-26 23:17 UTC, hsha0 commented on src/main/java/codeu/controller/UsersServlet.java
> +    userBuilder.setLastName(user.getLastName());
I don't think we have the first name and the last name before. They should also be assigned through request.getParameter.

2018-04-26 23:17 UTC, hsha0 commented on src/main/java/codeu/controller/UsersServlet.java
> +}
I changed the filename to UserServlet.java. Be careful when you solve the conflicts.

2018-04-26 23:17 UTC, hsha0 commented on src/main/java/codeu/model/data/User.java
> +		private final String pictureURL;
Indentation here 6 spaces

2018-04-26 23:17 UTC, hsha0 commented on src/main/java/codeu/model/data/User.java
> +		 * @param newPictureURL the URL of the profile picture of this User
indentation here 6 spaces

2018-04-26 23:17 UTC, hsha0 commented on src/main/java/codeu/model/data/User.java
>  }
All indentations should be 2-space standard

2018-04-26 23:17 UTC, hsha0 commented on src/test/java/codeu/controller/UserServletTest.java
> +        Assert.assertEquals(userArgumentCaptor.getValue().getPictureURL(), "www.url.com");
We also need to check the first name and the last name, right?

2018-04-26 23:17 UTC, hsha0 commented on src/test/java/codeu/controller/UserServletTest.java
> +        Mockito.verify(mockResponse).sendRedirect("/about");
I used /user in my UserServlet.java. You can choose either one of them when merging.

2018-04-27 15:09 UTC, hsha0 reviewed
Need tests for first name and last name, other LGTM. You can merge after adding the tests.

2018-04-27 15:09 UTC, hsha0 commented on src/test/java/codeu/controller/UserServletTest.java
> +
getParameter("first") and getParameter("last")

2018-04-27 15:09 UTC, hsha0 commented on src/test/java/codeu/controller/UserServletTest.java
> +
assertEquals for first name and last name

2018-04-27 15:09 UTC, hsha0 approved these changes

2018-04-27 15:19 UTC, hsha0 commented
Also need to add Assert.assertEquals() for first and last name

2018-04-27 15:28 UTC, hsha0 commented
I am wondering why when Running codeu.model.store.persistence.PersistentDataStoreTest, it shows INFO: Local Datastore initialized: 
	Type: High Replication
	Storage: In-memory

2018-04-27 15:33 UTC, CalamariDude commented
Hmmm, looked around for significant places where there could be high usage, couldn't find anything. Tried googling it, seems like its a datastore related problem.  @TylerSandman any ideas?

2018-04-27 15:46 UTC, hsha0 commented
And for adding the user to persistenceDataStore, why we don't use addUser() function?
/** Add a new user to the current set of users known to the application. */
  public void addUser(User user) {
    users.add(user);
    persistentStorageAgent.writeThrough(user);
  }

2018-04-27 19:22 UTC, CalamariDude commented
You mean for updating the user?

2018-04-27 20:32 UTC, hsha0 commented
Yeah, can we just use addUser function instead of updateUser?

2018-04-29 22:21 UTC, merged